export const backgroundColor = "#f2faff"
export const primaryColor = "#0080ff"
export const primaryElevatedColor = "#1a8cff"
export const primaryHoverdColor = "#f0f7ff"
export const primarySelectedColor = "#e0f0ff"
export const supportingTextColor = "#4d4d4d"
export const borderColor = "#c6cacc"
